- hosts: all
  tags:
    - run_docker
  vars_files:
    - secrets.yaml
  tasks:
    - name: Run dol baumanec syb docker container
      docker_container:
        name: dol-baumanec-syb
        image: twobrowin/dol-baumanec-syb:v2.0.1-no-kb-upd
        state: started
        detach: yes
        restart: yes
        recreate: yes
        env:
          BOT_TOKEN: "{{ bot_token }}"
          SHEETS_ACC_JSON: "{{ sheet_acc_json | string }}"

          SHEETS_NAME: "Таблица бота бауманец для ШМБ"
          SHAEET_PHONE: "Номера телефонов"
          SHEET_KEYBOARD: "Команды бота"

          UPDATE_KEYBOARD_TIMEOUT: "3600"
