# Load images
- hosts: all
  tags:
    - docker_img
  tasks:
    - name: Create images directory
      tags:
        - docker_img_copy
      file:
        path:  ~/img/
        state: directory

    - name: Copy docker images files
      tags:
        - docker_img_copy
      copy:
        src:  ./img/
        dest: ~/img/
        directory_mode: yes
    
    - name: Load docker images
      tags:
        - docker_img_load
      docker_image:
        name: "{{ item | split('/') | last | split('_') | first | split('=') | join('/') }}"
        tag: "{{ item | split('/') | last | split('_') | last }}"
        load_path: "~/img/{{ item | split('/') | last  }}"
        source: load
      with_fileglob:
        - ./img/*
    
    - name: Remove docker images files
      tags:
        - docker_img_rm
      file:
        path: "~/img/{{ item | split('/') | last  }}"
        state: absent
      with_fileglob:
        - ./img/*

# Run images
- hosts: all
  tags:
    - run_docker
  vars_files:
    - secrets.yaml
  tasks:
    - name: Run dol baumanec syb docker container
      docker_container:
        name: dol-baumanec-syb
        image: dol-baumanec-syb:v1.5
        state: started
        detach: yes
        restart: yes
        recreate: yes
        env:
          BOT_TOKEN: "{{ bot_token }}"
          SHEETS_ACC_JSON: "{{ sheet_acc_json | string }}"

          SHEETS_NAME: "Таблица бота бауманец для ШМБ"
          SHAEET_PHONE: "Номера телефонов"
          SHEET_KEYBOARD: "Команды бота"

          UPDATE_KEYBOARD_TIMEOUT: "3600"
          UPDATE_PHONES_TIMEOUT: "3600"
    
